name: investment_tracking
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  binance_pay: ^0.0.3
  curved_navigation_bar: ^1.0.6
  http: ^1.5.0
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  fl_chart: 0.64.0
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
